# Generated by Django 5.2.15 on 2026-07-06 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('comentario', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContratoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo', to='comisiones.asesor')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='comisiones.estado')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True, db_index=True, help_text='ID original del Excel.', null=True)),
                ('facturacion', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('pct_comision', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('comision_total', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('portafolio', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('fecha_separacion', models.DateField(blank=True, null=True)),
                ('fecha_cobro', models.DateField(blank=True, null=True)),
                ('flag_semanal', models.BooleanField(default=False)),
                ('comentarios', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='comisiones.asesor')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones', to='comisiones.cliente')),
                ('contrato_modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisiones.contratomodelo')),
                ('coordinador_leads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones_leads', to='comisiones.asesor')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisiones.metodopago')),
            ],
            options={
                'ordering': ['-fecha_cobro', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EtapaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField()),
                ('usuario', models.CharField(blank=True, max_length=160)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='comisiones.operacion')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('calle', models.CharField(blank=True, help_text='Calle y número exterior (texto libre).', max_length=200)),
                ('numero_interior', models.CharField(blank=True, max_length=40)),
                ('colonia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='comisiones.colonia')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='comisiones.tipopropiedad')),
            ],
        ),
        migrations.AddField(
            model_name='operacion',
            name='propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones', to='comisiones.propiedad'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='status_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comisiones.statuscierre'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='status_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comisiones.statuspago'),
        ),
        migrations.CreateModel(
            name='TarifaReparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiario_tipo', models.CharField(choices=[('asesor', 'Asesor'), ('coordinador', 'Coordinador'), ('coordinador_leads', 'Coordinadora de leads')], max_length=20)),
                ('pct', models.DecimalField(decimal_places=4, help_text='Fracción sobre la comisión total (ej. 0.60).', max_digits=6)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fin', models.DateField(blank=True, help_text='Vacío = vigente.', null=True)),
                ('contrato_modelo', models.ForeignKey(blank=True, help_text="Solo aplica al beneficiario 'asesor'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='comisiones.contratomodelo')),
            ],
            options={
                'ordering': ['beneficiario_tipo', '-vigencia_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiario_tipo', models.CharField(choices=[('asesor', 'Asesor'), ('coordinador', 'Coordinador'), ('coordinador_leads', 'Coordinadora de leads'), ('eq', 'Espacio Querido')], max_length=20)),
                ('pct_aplicado', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participaciones', to='comisiones.asesor')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='comisiones.operacion')),
                ('tarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisiones.tarifareparto')),
            ],
        ),
        migrations.AddField(
            model_name='operacion',
            name='tipo_operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comisiones.tipooperacion'),
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='comisiones.municipio')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'municipio')},
            },
        ),
        migrations.AddField(
            model_name='colonia',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colonias', to='comisiones.zona'),
        ),
        migrations.AlterUniqueTogether(
            name='colonia',
            unique_together={('nombre', 'zona')},
        ),
    ]
